### ISSUE TITLE
Background color of login page

### ISSUE THREAD

**Issue by quiloos39** [quiloos39/my-study-peer-ui#1]
When u rotate screen, background color in login page doesn't cover whole page

Here is the implementation

https://github.com/quiloos39/my-study-peer-ui/blob/master/src/pages/login.js#L7

Here is visual of the bug

![](https://i.imgur.com/sDRxmGh.png)

**Comment by Daniel-Singer** [comment]
Hi @quiloos39 ! So as i understood, when you switch from portrait to landscape mode, the screen looks like this right? Is it ok if i try to get that done for you?

**Comment by quiloos39** [comment]
Yes, you are correct and of course you can do it we are open to every help we can get.

**Comment by Daniel-Singer** [comment]
Awesome, thank you ! Just sent a PR. Hope i could help

**Comment by quiloos39** [comment]
Thanks for your work i accidenly merged package-lock.json too 😄😄 
I will probably fix that in next commit
